name: myapp

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sabarmenanti
      MYSQL_DATABASE: perpustakaan
      MYSQL_USER: sabar
      MYSQL_PASSWORD: menanti
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - net-myapp

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - net-myapp

networks:
  net-myapp:
